const myprojects = [
  {
    id: 1,
    title: "Wheather App",
    category: "JS",
    imgpath: "/Wheather.jpg",
    P: "this is a API dependent wheather app works 24/7",
    git: "https://github.com/ousey-ousey/weather-app-api",
  },
  {
    id: 2,
    title: "bar of navigations",
    category: "JS",
    imgpath: "/bar-succes.jpg",
    P: "this is a desine for bar notification desappear after 5s ,check it now!",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 3,
    title: "FRQs",
    category: "JS",
    imgpath: "/FQRs.jpg",
    P: "this is a simple Fqrs that can be swiched from one selection and multible.",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 4,
    title: "calculator",
    category: "css",
    imgpath: "/calc.jpg",
    P: "this is just css and html working calc can u belive it ?!",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 5,
    title: "QR generator",
    category: "JS",
    imgpath: "/qr-code-gene.jpg",
    P: "this is  qr code generator of text input",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 6,
    title: "Random pass generator",
    category: "JS",
    imgpath: "/random-pass.jpg",
    P: "this is  random pass generator!",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 7,
    title: "Random color generator",
    category: "JS",
    imgpath: "/random-color.jpg",
    P: "this is  random color generator!",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 8,
    title: " Most Acurate age calculator",
    category: "JS",
    imgpath: "/age-calc.jpg",
    P: "this is   age calculator that is perfect to know acurate age!",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 9,
    title: " React Protifolio",
    category: "React",
    imgpath: "/react-1.jpg",
    P: "this is   REACT protifoli that u watch throght it it took me 12h to 14h along 3days!",
    git: "https://github.com/ousey-ousey",
  },
];
export default myprojects;
