const myprojects = [
  {
    id: 1,
    title: " React Portfolio",
    category: "React",
    imgpath: "/react-1.jpg",
    P: "this is   REACT portfolio that u watch thought it it took me 12h to 14h along 3days!",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 2,
    title: " social media web",
    category: ["React", "Firebase"],
    link: "https://second-one-three.vercel.app/",
    imgpath: "/social.jpg",
    P: "social media website stimulator easy to use ,dark mode,functioning and simple ",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 3,
    title: "Team web design",
    category: ["React"],
    link: "https://siriuseg.vercel.app/",
    imgpath: "/sirios.jpg",
    P: "A design for team of digital services ",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 4,
    title: "E-learning web design",
    category: ["Next", "tailwind"],
    link: "https://codixa.vercel.app/",
    imgpath: "/registration.jpg",
    P: "A design for E learning and courses ",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 5,
    title: " Muti step form (frontend monetor level 4)",
    category: ["React"],
    link: "https://multi-step-form-main-vite-frontend-ndwb.vercel.app/",
    imgpath: "/multi.jpg",
    P: " Miti step form using react and react router MUI , advanced level in frotend monetor",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 6,
    title: " To do&Firebase& database",
    category: ["React", "Firebase"],
    link: "https://react-firebase-pro-2-hmzc7uxvb-yousefs-projects-0a4c00cd.vercel.app/",
    imgpath: "/black.jpg",
    P: "this is   REACT Firebase databaseusing sign up and in data send and vertification of email, the hard wep everyone have an email and have his to do lists that is saved in database remove and add tasks check it now",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 7,
    title: "store & cart & page (node js and express)",
    category: "React",
    link: "https://level5-redux-react-store.vercel.app/",
    imgpath: "/store.jpg",
    P: "this is a desine for complete functioning store",
    git: "https://github.com/ousey-ousey",
  },

  {
    id: 8,
    title: " VR Landing page",
    category: ["tailwind", "css"],
    link: "https://vr-landing-fin.vercel.app/",
    imgpath: "/VR.jpg",
    P: "Vr Landing with absolute modern design!",
    git: "https://github.com/ousey-ousey",
  },
  {
    id: 9,
    title: "Weather App",
    category: "JS",
    imgpath: "/Wheather.jpg",
    P: "this is a API dependent weather app works 24/7",
    git: "https://github.com/ousey-ousey/weather-app-api",
  },
];
export default myprojects;
